# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ff5b50820f2350c6621a948fe3b09aadd3ea645c11c5b4859bdb401110b7829f844eec3dfb86cba2f23b1b4f3b2f290f21d3485b438db6033edf1b08ca14c1

test:
  secret_key_base: ceb9315cd03153ba49e22b1486e133b0849533e44d5d9c4a4808bc10b1a3a49b6bb4f4f0450a5fdb6d8e41490ca0a92ba9b736ffce2adbfab9512493781227f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
